"""
Jaeger Trace Analyzer
Fetches and analyzes trace data from Jaeger to extract timing breakdowns.
Particularly useful for separating ML inference time from other processing time.

Usage:
    python testing/AI4I/loadtesting/jaeger_analyzer.py --trace-id e6887e0d7ba9f00d00414608926747f7
    python testing/AI4I/loadtesting/jaeger_analyzer.py --metrics-file testing/AI4I/logs/nmt_metrics_staging_*.json
"""

import argparse
import json
import os
import sys
from typing import Dict, List, Optional
import statistics

try:
    import requests
except ImportError:
    print("ERROR: requests library not found. Install with: pip install requests")
    sys.exit(1)


class JaegerAnalyzer:
    def __init__(self, jaeger_base_url: str = "https://staging.ai4inclusion.org"):
        """
        Initialize Jaeger analyzer.

        Args:
            jaeger_base_url: Base URL for Jaeger instance (default: staging)
        """
        self.base_url = jaeger_base_url.rstrip("/")
        self.api_url = f"{self.base_url}/jaeger/api/traces"

    def fetch_trace(self, trace_id: str) -> Optional[Dict]:
        """
        Fetch a single trace from Jaeger.

        Args:
            trace_id: Hexadecimal trace ID

        Returns:
            Trace data as dict, or None if not found
        """
        try:
            response = requests.get(f"{self.api_url}/{trace_id}", timeout=10)
            response.raise_for_status()
            return response.json()
        except requests.RequestException as e:
            print(f"Error fetching trace {trace_id}: {e}")
            return None

    def analyze_trace(self, trace_data: Dict) -> Dict:
        """
        Analyze a trace to extract timing breakdowns.

        Returns:
            {
                "total_duration_ms": float,
                "inference_duration_ms": float,
                "non_inference_duration_ms": float,
                "spans": [{"name": str, "duration_ms": float}, ...],
                "trace_id": str
            }
        """
        if not trace_data or "data" not in trace_data:
            return {"error": "Invalid trace data"}

        traces = trace_data["data"]
        if not traces:
            return {"error": "No traces found"}

        trace = traces[0]  # First trace
        spans = trace.get("spans", [])

        if not spans:
            return {"error": "No spans in trace"}

        # Find root span (parent of all spans)
        root_span = None
        for span in spans:
            if not span.get("references"):  # No parent
                root_span = span
                break

        if not root_span:
            root_span = spans[0]  # Fallback to first span

        total_duration_us = root_span.get("duration", 0)
        total_duration_ms = total_duration_us / 1000.0

        # Analyze all spans
        span_details = []
        inference_duration_ms = 0.0

        for span in spans:
            span_name = span.get("operationName", "unknown")
            duration_us = span.get("duration", 0)
            duration_ms = duration_us / 1000.0

            span_details.append({
                "name": span_name,
                "duration_ms": round(duration_ms, 2)
            })

            # Detect ML inference spans - only count actual ML server calls
            # triton.* = Triton inference server (the actual GPU/ML work)
            # Exclude: API endpoint names (POST /api/.../inference), application logic (nmt.inference)
            if any(keyword in span_name.lower() for keyword in ["triton.inference", "triton.infer", "ml.predict", "gpu.infer"]):
                inference_duration_ms += duration_ms

        non_inference_duration_ms = total_duration_ms - inference_duration_ms

        return {
            "trace_id": trace.get("traceID", "unknown"),
            "total_duration_ms": round(total_duration_ms, 2),
            "inference_duration_ms": round(inference_duration_ms, 2),
            "non_inference_duration_ms": round(non_inference_duration_ms, 2),
            "inference_percentage": round((inference_duration_ms / total_duration_ms * 100), 2) if total_duration_ms > 0 else 0,
            "non_inference_percentage": round((non_inference_duration_ms / total_duration_ms * 100), 2) if total_duration_ms > 0 else 0,
            "span_count": len(spans),
            "spans": sorted(span_details, key=lambda x: x["duration_ms"], reverse=True)[:10]  # Top 10 slowest spans
        }

    def analyze_metrics_file(self, metrics_file: str, sample_size: int = 100) -> None:
        """
        Analyze traces from a metrics JSON file and calculate non-inference metrics.

        Args:
            metrics_file: Path to metrics JSON file generated by load test
            sample_size: Number of successful traces to sample for analysis (default: 100)
        """
        if not os.path.exists(metrics_file):
            print(f"ERROR: Metrics file not found: {metrics_file}")
            return

        with open(metrics_file, "r") as f:
            metrics = json.load(f)

        failed_traces = metrics.get("failed_traces", [])
        slow_traces = metrics.get("slow_traces", [])
        successful_traces = metrics.get("successful_traces", [])

        print("\n" + "="*80)
        print("JAEGER TRACE ANALYSIS - NON-INFERENCE TIMING METRICS")
        print("="*80)
        print(f"Load Test Summary:")
        print(f"  Total Requests: {metrics.get('total_requests', 'N/A')}")
        print(f"  Successful: {metrics.get('successful', 'N/A')} ({metrics.get('success_rate', 'N/A')})")
        print(f"  Failed: {metrics.get('failed', 'N/A')}")
        print(f"  Duration: {metrics.get('duration_seconds', 'N/A')}s")

        # Analyze sample of slow traces to get non-inference metrics
        all_non_inference_times = []
        all_inference_times = []
        all_total_times = []

        # Prefer slow traces, but fall back to successful traces if no slow traces exist
        if slow_traces:
            traces_to_analyze = slow_traces[:sample_size]
            trace_source = "slow requests (>5s)"
        elif successful_traces:
            traces_to_analyze = successful_traces[:sample_size]
            trace_source = "successful requests"
        else:
            traces_to_analyze = []
            trace_source = None

        if traces_to_analyze:
            print(f"\n📊 ANALYZING {len(traces_to_analyze)} TRACES FOR NON-INFERENCE METRICS...")
            print(f"Trace source: {trace_source}")
            print("-"*80)

            for i, trace_info in enumerate(traces_to_analyze, 1):
                trace_id = trace_info["trace_id"]
                trace_data = self.fetch_trace(trace_id)

                if trace_data:
                    analysis = self.analyze_trace(trace_data)
                    if "error" not in analysis:
                        all_non_inference_times.append(analysis["non_inference_duration_ms"])
                        all_inference_times.append(analysis["inference_duration_ms"])
                        all_total_times.append(analysis["total_duration_ms"])

                        if i <= 5:  # Show details for first 5
                            print(f"\n{i}. Trace: {self.base_url}/jaeger/trace/{trace_id}")
                            print(f"   Total: {analysis['total_duration_ms']}ms | Inference: {analysis['inference_duration_ms']}ms | Non-Inference: {analysis['non_inference_duration_ms']}ms")
                            top_spans = ', '.join([f"{s['name']} ({s['duration_ms']}ms)" for s in analysis['spans'][:3]])
                            print(f"   Top spans: {top_spans}")

            if all_non_inference_times:
                sorted_non_inf = sorted(all_non_inference_times)
                sorted_inf = sorted(all_inference_times)
                sorted_total = sorted(all_total_times)
                n = len(sorted_non_inf)

                print(f"\n" + "="*80)
                print("🎯 NON-INFERENCE TIMING METRICS (Excluding ML/GPU Time)")
                print("="*80)
                print(f"Sample Size: {n} requests")
                print(f"\n{'Metric':<20} {'Total Time':<20} {'Inference Time':<20} {'Non-Inference Time':<20}")
                print("-"*80)

                print(f"{'Min':<20} {min(sorted_total):>15.2f}ms {min(sorted_inf):>15.2f}ms {min(sorted_non_inf):>15.2f}ms")
                print(f"{'Max':<20} {max(sorted_total):>15.2f}ms {max(sorted_inf):>15.2f}ms {max(sorted_non_inf):>15.2f}ms")
                print(f"{'Average':<20} {statistics.mean(sorted_total):>15.2f}ms {statistics.mean(sorted_inf):>15.2f}ms {statistics.mean(sorted_non_inf):>15.2f}ms")
                print(f"{'Median':<20} {statistics.median(sorted_total):>15.2f}ms {statistics.median(sorted_inf):>15.2f}ms {statistics.median(sorted_non_inf):>15.2f}ms")

                if n > 20:
                    p95_total = sorted_total[int(n * 0.95)]
                    p95_inf = sorted_inf[int(n * 0.95)]
                    p95_non_inf = sorted_non_inf[int(n * 0.95)]
                    print(f"{'P95':<20} {p95_total:>15.2f}ms {p95_inf:>15.2f}ms {p95_non_inf:>15.2f}ms")

                if n > 100:
                    p99_total = sorted_total[int(n * 0.99)]
                    p99_inf = sorted_inf[int(n * 0.99)]
                    p99_non_inf = sorted_non_inf[int(n * 0.99)]
                    print(f"{'P99':<20} {p99_total:>15.2f}ms {p99_inf:>15.2f}ms {p99_non_inf:>15.2f}ms")

                if n > 1:
                    print(f"{'Std Dev':<20} {statistics.stdev(sorted_total):>15.2f}ms {statistics.stdev(sorted_inf):>15.2f}ms {statistics.stdev(sorted_non_inf):>15.2f}ms")

                print(f"\n" + "="*80)
                print("📈 PERFORMANCE BREAKDOWN")
                print("="*80)
                avg_total = statistics.mean(sorted_total)
                avg_inf = statistics.mean(sorted_inf)
                avg_non_inf = statistics.mean(sorted_non_inf)

                inf_pct = (avg_inf / avg_total * 100) if avg_total > 0 else 0
                non_inf_pct = (avg_non_inf / avg_total * 100) if avg_total > 0 else 0

                print(f"Average Total Response Time:      {avg_total:.2f}ms")
                print(f"  ├─ ML Inference Time:            {avg_inf:.2f}ms ({inf_pct:.1f}%)")
                print(f"  └─ Non-Inference Time (API):     {avg_non_inf:.2f}ms ({non_inf_pct:.1f}%)")
                print(f"\n💡 Non-inference overhead is {non_inf_pct:.1f}% of total response time")
        else:
            print(f"\n⚠️  No traces available for analysis")
            print(f"   - Slow traces (>5s): {len(slow_traces)}")
            print(f"   - Successful traces: {len(successful_traces)}")
            print(f"   - Failed traces: {len(failed_traces)}")
            if not slow_traces and not successful_traces and not failed_traces:
                print(f"\n💡 Trace IDs may not be captured. Check that:")
                print(f"   1. Server returns trace ID in response headers (X-Trace-Id or traceparent)")
                print(f"   2. nmt_loadtesting.py extracts and passes trace_id to metrics.record_request()")

        # Show failed traces
        if failed_traces:
            print(f"\n" + "="*80)
            print(f"📛 FAILED REQUESTS ({len(failed_traces)} traces)")
            print("="*80)
            for trace_info in failed_traces[:5]:  # Analyze first 5
                trace_id = trace_info["trace_id"]
                print(f"\n🔍 Trace: {self.base_url}/jaeger/trace/{trace_id}")
                print(f"   Status: {trace_info['status_code']} | Response Time: {trace_info['response_time']:.2f}s")
                print(f"   Error: {trace_info.get('error', 'N/A')}")

                trace_data = self.fetch_trace(trace_id)
                if trace_data:
                    analysis = self.analyze_trace(trace_data)
                    if "error" not in analysis:
                        print(f"   Breakdown: Total={analysis['total_duration_ms']}ms, Inference={analysis['inference_duration_ms']}ms, Non-Inference={analysis['non_inference_duration_ms']}ms")


def main():
    parser = argparse.ArgumentParser(description="Analyze Jaeger traces for load testing")
    parser.add_argument("--trace-id", help="Single trace ID to analyze")
    parser.add_argument("--metrics-file", help="Path to metrics JSON file from load test")
    parser.add_argument("--jaeger-url", default="https://staging.ai4inclusion.org",
                       help="Jaeger base URL (default: staging)")
    parser.add_argument("--env", default="staging", help="Environment: staging or sandbox")

    args = parser.parse_args()

    # Auto-detect Jaeger URL from environment
    if args.env == "sandbox":
        jaeger_url = "https://sandbox.ai4inclusion.org"
    else:
        jaeger_url = args.jaeger_url

    analyzer = JaegerAnalyzer(jaeger_base_url=jaeger_url)

    if args.trace_id:
        print(f"Fetching trace: {args.trace_id}")
        trace_data = analyzer.fetch_trace(args.trace_id)
        if trace_data:
            analysis = analyzer.analyze_trace(trace_data)
            print(json.dumps(analysis, indent=2))
        else:
            print("Failed to fetch trace")
            sys.exit(1)

    elif args.metrics_file:
        analyzer.analyze_metrics_file(args.metrics_file)

    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
